# 
# Actual Deployment Scheme will be something like this, 
# but because this is just an examle we will use 'localhost' only
# 
# handy_scheme:
#   'web1.app.com': ['web']
#   'web2.app.com': ['web']
#   'db.app.com': ['db']
# 
# Vagrant is configured to use 10.11.12.13 as IP.
handy_scheme:
  '10.11.12.13': ['basic', 'web', 'db']

ssh:
  '10.11.12.13':
    :user: 'root'
    :password: 'vagrant'

# 
# You can also define here any arbitrary variables
# 
# app_path: /tmp/cm_example_app
